### ISSUE TITLE
VSC can't load the file

### ISSUE THREAD

**Issue by rcrooks** [FraDepe/Dark-Yellow-Theme#1]
Hi @FraDepe just to let you know, I installed this and tried to select it, but a message popped up saying VS Code couldn't load it. Not sure if it's an issue with the theme or the package. Best, Robert

**Comment by FraDepe** [comment]
Thank you. I forgot some not closed parenthesis somewhere. I'll fix that and some color and i'll publish it again.

**Comment by FraDepe** [comment]
Should be fixed now
